# Generated by Django 3.2.16 on 2022-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the user', max_length=200)),
                ('email', models.CharField(help_text='Email of the user', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Address of the user', null=True)),
            ],
        ),
    ]
